name: flutter_icon_shadow
description: flutter icon shadow.
version: 2.0.4
homepage: https://github.com/chenasraf/flutter_icon_shadow

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: null
