name: flutter_icon_shade
description: flutter icon shadow.
version: 2.0.1
homepage: https://github.com/chenasraf/flutter_flutter_icon_shade

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

flutter:
